# Menggunakan builder khusus dari Caddy untuk memasang plugin
FROM caddy:builder-alpine AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

# Memindahkan hasil build ke image alpine yang bersih
FROM caddy:alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy